// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import JobController from "./job_controller.js"
application.register("job", JobController)

import MobileNavbarController from "./mobile_navbar_controller.js"
application.register("mobile-navbar", MobileNavbarController)
